Clear sensitive exif metadata from jpeg files
digabi/exam-engine pull request #3085
Opened 2023-07-11 12:27 UTC by tobiasson

2023-07-13 06:05 UTC, mtreinik commented on packages/rendering/src/utils/exifDataAndImageHandler.ts
> +    newExifData['0th'][exif.TagValues.ImageIFD.DocumentName] = ''
Varmaan mielipidekysymys, mutta kumpi olisi luettavampi, tämä vai jotain tyyliin:
`Object.assign(newExifData['0th'], { exif.TagValues.DocumentName: '', exif.TagValues.ImageDescription: '', ... }`?

2023-07-27 07:49 UTC, eeroan requested changes

2023-07-27 07:49 UTC, eeroan commented on packages/rendering/src/utils/exifDataAndImageHandler.ts
> +    rm(sourceFilePath, { force: true }, (err) => {
käytä `fs/promises` niin toimii await `rm(...)`, `await readFile` ja `await writeFile`.

Tuossa on nimittäin semmonen bugi tällä hetkellä, että rm jää ajamaan taustalle vaikka failaisi

2023-07-27 07:49 UTC, eeroan commented on packages/rendering/src/utils/exifDataAndImageHandler.ts
> +    newExifData['0th'][exif.TagValues.ImageIFD.DocumentName] = ''
ja vieläpä tähän tyyliin:

`Object.assign(newExifData['0th'], { exif.TagValues: { DocumentName: '', ImageDescription: '', ... }})`

Onko ylipäätänsä noita kenttiä pakko määritellä? Mitä käy jos sanoo `newExifData['0th'] = undefined`

2023-07-27 07:49 UTC, eeroan commented on packages/rendering/src/utils/exifDataAndImageHandler.ts
> +  if (newExifData && newExifData['0th']) {
Voi myös sanoa `if (newExifData?.['0th'])`

2023-08-17 09:20 UTC, eeroan requested changes

2023-08-17 09:20 UTC, eeroan commented on packages/rendering/src/utils/exifDataAndImageHandler.ts
> +    ...(exifSource?.['0th'] && { '0th': getImageIFData(exifSource?.['0th']) }),
get on huono nimi, koska tässä mutatoidaan. Oisko joku appendImageIFData? Onko myös jälkemmäinen ? turha, koska sinne asti ei päästä jos exidSource on undefined

2023-08-17 09:20 UTC, eeroan commented on packages/rendering/src/utils/exifDataAndImageHandler.ts
> +    return await readFile(src).then(data => data.toString('binary'))
oisko kivempi näin:
```
const data = await readFile(src)
return data.toString('binary')
```

2023-08-18 06:27 UTC, eeroan requested changes

2023-08-18 06:27 UTC, eeroan commented on packages/rendering/src/utils/exifDataAndImageHandler.ts
> +  if (['.jpg'].includes(path.extname(sourceFilePath))) {
Varmaan ajateltu tulevaisuutta, mutta nyt ehkä selkeempää sanoa `if((path.extname(sourceFilePath) === '.jpg')`

2023-08-18 06:27 UTC, eeroan commented on packages/rendering/src/utils/exifDataAndImageHandler.ts
> +  return newExifData
tän voi inlainata

2023-08-18 06:36 UTC, tobiasson commented on packages/rendering/src/utils/exifDataAndImageHandler.ts
> +  if (['.jpg'].includes(path.extname(sourceFilePath))) {
Totta, oli ajateltu tulevaisuutta

2023-08-18 06:37 UTC, tobiasson commented on packages/rendering/src/utils/exifDataAndImageHandler.ts
> +  return newExifData
Done

2023-08-18 09:35 UTC, merged